In [1]:
from selenium import webdriver
import pandas as pd
import time 
from tqdm import tqdm

In [2]:
FILE_PATH_FOLDER = r"C:\Users\sumit\Dt\chromedriver.exe"
search_query = 'https://www.naukri.com/data-analyst-jobs-in-bangalore?k=Data%20Analyst&l=Bangalore'
driver = webdriver.Chrome(executable_path= r"C:\Users\sumit\Dt\chromedriver.exe")

In [3]:
driver.get(search_query)

In [4]:
#“Data Analyst” Job position in “Bangalore” location

df=pd.DataFrame(columns=['job-title', 'job-location', 'company_name', 'experience_required','url'] )#Creating empty df

#Getting the required data
for lst in tqdm(driver.find_elements_by_css_selector(".jobTuple.bgWhite.br4.mb-8")):  
    
    try:
        jt=lst.find_element_by_css_selector("a.title.fw500.ellipsis").text
    except:
        jt ="Nan"
    try:
        jl=lst.find_element_by_css_selector(".fleft.grey-text.br2.placeHolderLi.location").text
    except:
        jl="NaN"
    try:
        cn=lst.find_element_by_css_selector("a.subTitle.ellipsis.fleft").text
    except:
        cn="Nan"
    try:
        er=lst.find_element_by_css_selector(".fleft.grey-text.br2.placeHolderLi.experience").text
    except:
        er="NaN"
    try:
        url=lst.find_element_by_tag_name('a').get_attribute("href")
    except:
        url='NaN'

#Putting those data into dataframe
    df.loc[len(df)]=[jt,jl,cn,er,url]

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.35it/s]

In [5]:
df

,job-title,job-location,company_name,experience_required,url
0,Business Data Analyst - MIS & Reporting,"Mumbai, Bangalore/Bengaluru",INTERTRUST GROUP,3-8 Yrs,https://www.naukri.com/job-listings-business-d...
1,Senior Data Analyst - Data Lineage,Bangalore/Bengaluru,Opex Global Services,5-10 Yrs,https://www.naukri.com/job-listings-senior-dat...
2,Data Analyst - Informatica MDM,Bangalore/Bengaluru,Shell India Markets Private Limited,6-9 Yrs,https://www.naukri.com/job-listings-data-analy...
3,Data Analyst,"Noida, Kolkata, Hyderabad/Secunderabad, Pune, ...",AG Technologies pvt Ltd,0-2 Yrs,https://www.naukri.com/job-listings-data-analy...
4,Data Analyst,"Noida, Kolkata, Hyderabad/Secunderabad, Pune, ...",AG Technologies pvt Ltd,0-2 Yrs,https://www.naukri.com/job-listings-data-analy...
5,Excel VBA Jobs Bangalore | VBA data analyst Jobs,"Mysore/Mysuru, Coimbatore, Bangalore/Bengaluru",Mind Circus Innovation,0-1 Yrs,https://www.naukri.com/job-listings-excel-vba-...
6,Data Analyst (2positions)//immediate Joiners//...,Bangalore/Bengaluru,Tech Mahindra Ltd.,4-8 Yrs,https://www.naukri.com/job-listings-data-analy...
7,Business/Data Analyst - SSE/LA,Bangalore/Bengaluru,CGI Information Systems and Management Consult...,2-5 Yrs,https://www.naukri.com/job-listings-business-d...
8,Business Data Analyst,"Chennai, Bangalore/Bengaluru, Mumbai (All Areas)","dotSolved India Pvt., Ltd.",9-13 Yrs,https://www.naukri.com/job-listings-business-d...
9,Data Analyst,Bangalore/Bengaluru,Myntra Designs Pvt. Ltd.,3-5 Yrs,https://www.naukri.com/job-listings-data-analy...
10,Data Analyst,Bangalore/Bengaluru,Myntra Designs Pvt. Ltd.,3-8 Yrs,https://www.naukri.com/job-listings-data-analy...
11,data analyst,"Pune, Chennai, Jaipur, Bangalore/Bengaluru",Disha Consultants,2-4 Yrs,https://www.naukri.com/job-listings-data-analy...
12,RC HIA - Data Analyst - A2,Bangalore/Bengaluru,Pricewaterhouse Coopers Private Limited,4-6 Yrs,https://www.naukri.com/job-listings-rc-hia-dat...
13,Procurement Data Analyst,Bangalore/Bengaluru,Schneider Electric,1-3 Yrs,https://www.naukri.com/job-listings-procuremen...
14,Data Analyst,Bangalore/Bengaluru,IBM India Pvt. Limited,5-10 Yrs,https://www.naukri.com/job-listings-data-analy...
15,Data Analyst/ Data Consultant (Various Levels ...,Bangalore/Bengaluru,DVSUM INDIA PRIVATE LIMITED,5-10 Yrs,https://www.naukri.com/job-listings-data-analy...
16,Data Scientist / Data Analyst -Business Analyst,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...",Inflexion Analytix Private Limited,0-3 Yrs,https://www.naukri.com/job-listings-data-scien...
17,Sr Data Analyst 1,Bangalore/Bengaluru,IHS Markit,3-6 Yrs,https://www.naukri.com/job-listings-sr-data-an...
18,Data Analyst / Sr. Data Analyst - SQL (work fr...,Bangalore Rural,Naukri Premium - Employer Services,1-6 Yrs,https://www.naukri.com/job-listings-data-analy...
19,Senior Data Analyst,"Hyderabad/Secunderabad, Bangalore/Bengaluru",Eze Castle Integration Services (Formerly Alph...,6-11 Yrs,https://www.naukri.com/job-listings-senior-dat...

In [6]:
FILE_PATH_FOLDER = r"C:\Users\sumit\Dt\chromedriver.exe"
search_query = 'https://www.naukri.com/data-scientist-jobs-in-bangalore?k=data%20scientist&l=bangalore'
driver = webdriver.Chrome(executable_path= r"C:\Users\sumit\Dt\chromedriver.exe")

In [7]:
driver.get(search_query)

In [8]:
#“Data Scientist” Job position in “Bangalore” location
df1=pd.DataFrame(columns=['job-title', 'job-location', 'company_name', 'experience_required','url'] )#Creating empty data frame

#Getting the required data
for lst in tqdm(driver.find_elements_by_css_selector(".jobTuple.bgWhite.br4.mb-8")):  
    
    try:
        jt=lst.find_element_by_css_selector("a.title.fw500.ellipsis").text
    except:
        jt ="Nan"
    try:
        jl=lst.find_element_by_css_selector(".fleft.grey-text.br2.placeHolderLi.location").text
    except:
        jl="NaN"
    try:
        cn=lst.find_element_by_css_selector("a.subTitle.ellipsis.fleft").text
    except:
        cn="Nan"
    try:
        er=lst.find_element_by_css_selector(".fleft.grey-text.br2.placeHolderLi.experience").text
    except:
        er="NaN"
    try:
        url=lst.find_element_by_tag_name('a').get_attribute("href")
    except:
        url='NaN'

#Putting those data into dataframe
    df1.loc[len(df1)]=[jt,jl,cn,er,url]

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  9.53it/s]

In [9]:
df1

,job-title,job-location,company_name,experience_required,url
0,Senior Data Scientist,Bangalore/Bengaluru,RedBus,5-8 Yrs,https://www.naukri.com/job-listings-senior-dat...
1,Immediate job opening - Senior Data Scientist,Bangalore/Bengaluru,RedBus,5-8 Yrs,https://www.naukri.com/job-listings-immediate-...
2,Senior Data Scientist,"Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru",Fractal Analytics,5-9 Yrs,https://www.naukri.com/job-listings-senior-dat...
3,Senior/ Lead Data Scientist,Bangalore/Bengaluru,Superior Group,6-11 Yrs,https://www.naukri.com/job-listings-senior-lea...
4,Lead Data Scientist,Bangalore/Bengaluru,FICO,6-11 Yrs,https://www.naukri.com/job-listings-lead-data-...
5,Lead Data Scientist,"Gurgaon/Gurugram, Bangalore/Bengaluru, Mumbai ...",Fractal Analytics,10-15 Yrs,https://www.naukri.com/job-listings-lead-data-...
6,Data analytics / Data scientist intern (work f...,"Kolkata, Bangalore/Bengaluru, Delhi / NCR",TalkValley LLC,0-5 Yrs,https://www.naukri.com/job-listings-data-analy...
7,Data Scientist - IBM Garage,Bengaluru/Bangalore,IBM India Pvt. Limited,2-6 Yrs,https://www.naukri.com/job-listings-data-scien...
8,Deputy Manager - Datalabs (Data Scientist),Bangalore/Bengaluru,HDFC LIFE INSURANCE COMPANY LIMITED,4-6 Yrs,https://www.naukri.com/job-listings-deputy-man...
9,Data Scientist,"Davangere, Bangalore/Bengaluru",Schneider Electric India Pvt. Ltd.,5-7 Yrs,https://www.naukri.com/job-listings-data-scien...
10,Senior Data Scientist with Python,"Kolkata, Chandigarh, Hyderabad/Secunderabad, P...",Next Bee Corporation,6-10 Yrs,https://www.naukri.com/job-listings-senior-dat...
11,Senior Data Scientist,Bangalore/Bengaluru,Publicis Groupe,2-5 Yrs,https://www.naukri.com/job-listings-senior-dat...
12,"Staff Data Scientist - Machine Learning, BigData",Bangalore/Bengaluru,Juniper Networks India Pvt Ltd,7-12 Yrs,https://www.naukri.com/job-listings-staff-data...
13,"Data Scientist - Machine Learning, BigData",Bangalore/Bengaluru,Juniper Networks India Pvt Ltd,5-10 Yrs,https://www.naukri.com/job-listings-data-scien...
14,Data Scientist (Visualization),Bangalore/Bengaluru,Aruba Networks,4-8 Yrs,https://www.naukri.com/job-listings-data-scien...
15,Data Scientist,"Mumbai, Gurgaon/Gurugram, Bangalore/Bengaluru",Fractal Analytics,3-7 Yrs,https://www.naukri.com/job-listings-data-scien...
16,Manager - Data Scientist,Bangalore/Bengaluru,Applied Materials,4-7 Yrs,https://www.naukri.com/job-listings-manager-da...
17,Junior/ Senior Data Scientist - Internet/ Onli...,Bangalore/Bengaluru,e-Hireo Global Pvt Ltd,10-15 Yrs,https://www.naukri.com/job-listings-junior-sen...
18,Lead Data Scientist,Bangalore/Bengaluru,Publicis Groupe,2-5 Yrs,https://www.naukri.com/job-listings-lead-data-...
19,Lead Data Scientist,Bangalore/Bengaluru,Cerner Corporation,4-7 Yrs,https://www.naukri.com/job-listings-lead-data-...

In [10]:
driver = webdriver.Chrome(executable_path= r"C:\Users\sumit\Dt\chromedriver.exe")

In [11]:
url='https://www.naukri.com/job-listings-hiring-java-programmers-and-data-scientists-sk-vedainfo-universal-technologies-pvt-ltd-hyderabad-secunderabad-bangalore-bengaluru-2-to-4-years-230521001057?src=jobsearchDesk&sid=16231313927347084&xp=1&px=1'
driver.get(url)
jd = driver.find_element_by_xpath("//div[@class='dang-inner-html']").text
jd

'- Increase your market value! Upgrade!\n\nGet Trained ON THE JOB in Supply Chain Domain, the hottest and fastest growing area in this current and post COVID world.\n\nGet employed by worlds leading global technology services and multinational company.\n\nIn INDIA, we are looking for 2 to 4 years experienced Java programmers and data scientists.\n\nNumber of positions: 25\nLocation: Bangalore and Hyderabad.\n\nYou will be trained in the following combinations ON THE JOB and help get certified:\n\nMandatory: Supply Chain Domain Functional Training and certification.\nJava - Angular + Springboot + No SQL\nJava - Dev ops tool (Git/Jenkins/etc)\nJava - AWS/Snowflake\nData Science - Python/Watson\n\nYou will be trained and deployed on the projects post certification.\nYou will be paid salary during the initial fulltime training period of 2 to 3 months.\nYou will be hired by our MNC client after 6 or 9 months period.\n\nVedainfo since 2006 is serving clients across the globe, with offices and operations in USA, India, Australia and New Zealand.\n\nIn collaboration and with authorization, we are hiring you for our MNC client.\n\nTo get started, please Share your resume to: MNC@Vedainfo.in'

In [12]:
url='https://www.naukri.com/job-listings-data-scientist-disruptive-digital-healthcare-platform-unnati-bangalore-bengaluru-5-to-8-years-080621002818?src=jobsearchDesk&sid=16231347341025209&xp=3&px=1'
driver.get(url)
jd = driver.find_element_by_xpath("//div[@class='dang-inner-html']").text
jd

"Roles and Responsibilities\nTo get transparent and quick status update, apply on : :https://rb.gy/4y8ayz\n\nAre you a high-performing, collaborative, results oriented and technologically savvy person who is keen on sales in the digital industry? Then this highly visible role is for you!\n\nOur client is the Health-tech initiative of India's largest business house. Started in 2015, it empowers healthcare providers and consumers in India. All healthcare monitoring services are made available through an app that will help connect doctors, hospitals, pharmacies, laboratories and consumers, enabling preventive and predictive healthcare. It helps the care-givers to track the entire patient journey from the initial appointment and maintaining their records, generating lab test reports to providing virtual consultation and home-care solutions. It is expected that this futuristic guide will strengthen doctor-patient relationship and enhance the in-clinic experience.\n\nAs a Data Scientist, you will build innovative analytics solutions and partner with product and business teams to improve existing solutions, and identify new opportunities to build data science solutions.\n\nWhat you will do:\nLeading and counselling the data science team in choosing the right approach for problem-solving.\nCollaborating with Data Scientists and Data engineers to enable deployment of solutions.\nBuilding POC's, IP’s and patents to create product differentiation using analytics and data science techniques.\nTransforming POC's into new product offerings\nArchitecting DS/ AI/ ML solutions for easy integration with product.\nEnsuring smooth operations of existing products.\nHelping business and product team with an understanding of consumer behaviour using internal data sets.\nMeasuring and articulating how data science initiatives improve business outcomes.\nTranslating business problems into analytics problems and further into defined tasks for the team to execute.\n\nDesired Candidate Profile\nWhat you need to have:\nB.E./ B.Tech - Min 65% or M.Tech\nExperience deploying DS/ ML/ AI solutions\nAbility to discover patterns in data and deliver impactful insights.\nAbility to convert high level business problems into analytics problems.\nExperience Managing data science teams.\nExperience working with business users / clients.\nHe/ She should have 5-8 years of experience in the Machine Learning space with background in healthcare (preferred but not essential).\nDesired Attributes Should have experience in Algorithms, NLP, Chatbots, Product Strategy, Advanced Analytics etc.\nShould have working exposure to Python, R, SAS, etc"

In [13]:
url='https://www.naukri.com/job-listings-senior-data-scientist-fittment-finder-bangalore-bengaluru-9-to-14-years-070621904162?src=jobsearchDesk&sid=16231347341025209&xp=4&px=1'
driver.get(url)
jd = driver.find_element_by_xpath("//div[@class='dang-inner-html']").text
jd

'We Urgently Looking for Sr. Data Scientist (Majorly with Scala) with TOP 10 largest company.\n\nSenior Data Scientist\nAs a Senior Data Scientist at , you will be responsible for owning of design and development of one or more data science solutions with appropriate choice of statistical and machine learning algorithms. Your resourcefulness, inquisitive aptitude, creative problem-solving capabilities and diligence in project delivery will be immensely valued.\n\nRoles Responsibilities\nResearch & develop Machine Learning models for defined solution.\nApply research methodologies to identify the Machine Learning models for the problem at hand.\nEnsures that appropriate documentation and training materials are created by close collaboration with Marketing and Product functions.\nWork collaboratively with engineering and product management in application, algorithm design and customer feedback.\n\nRequirement\nMasters/PhD in CS/IT/Data Science/EE/Mathematics and computing with 8+ years of experience\nCandidate should be in consulting Data Scientist role for 5 or more years\nExperience in implementing and deploying Machine Learning solutions in production\nAlong with Data Science, candidate is required to have prior experience in software development using object-oriented programming and database. Knowledge of BigData - Hive, Hadoop, Spark will be a plus.\nExperience of developing AI product will be a big plus.\nCandidate will have direct exposure to customers / partners / executives in SAI/CAI. Should be independent to work without directions.\nSelf-starter and self-motivated.\nSkills\nObject Oriented programming in any language - C++, Java, Python etc\nMust have good working knowledge of Relational Databases - especially complex joins.\nExperience of working with large datasets on database (RDBMS, Hive, Datawarehouse) for\nData science problem using python or other languages.\nProgramming language – Object Oriented programming in Python (must). Java, R, C/C++ is additional.\nData science skills – Unsupervised learning (must), supervised learning using classical machine learning, outlier detection, anomaly detection. Skills in NLP and deep learning are plus, but not a required criteria for selection.\nProficiency in data science solutions in retail / health care / media / telecom are preferred.\nProficiency in feature engineering and exploratory data analysis\nAbility to define problem statement and plan of execution of data science projects\nShould have strong communication and presentation skills.\n\nIf above profile is macthed with your current skills & epxerince..'

In [14]:
url='https://www.naukri.com/job-listings-data-scientist-placewell-consultants-mumbai-gurgaon-gurugram-bangalore-bengaluru-3-to-8-years-070621002691?src=jobsearchDesk&sid=16231347341025209&xp=5&px=1'
driver.get(url)
jd = driver.find_element_by_xpath("//div[@class='dang-inner-html']").text
jd

'Roles and Responsibilities\nCandidate must have strong experience Stats Modeling/Data science in 2 or more industry\nModeling: Experience in one or more of analytical tools such as Python, R, SAS etc\nEducation: Master’s – Economics, Statistics, Computer Science, Engineering from tier 1 institutes\nCombination of Stats Modeling + Machine Learning is highly preferred.\nCandidates who can join usless than 60 dayshighly preferred\nExperience:-\nLevel 11 – 2.6+ years (atleast recent 1.6+ yrs relevant in domain & Skills\nLevel 9 – 4 + years (atleast recent 3+ yrs relevant in domain & Skills)\n\n\nMust Have : Overall: 1. Delivey Perspective & Core Statistical / ML Programming Experience 2. Clarity of Interconnections between Tech landscaples & Science from ETL to Modelling To Visualization 3. Exposure to RFP / client requirement handling 4. Hardcore Data Science programming experience in at least 3 tools 5. Statistical presentations with ease 6. Adherence to Data Science SOP & Performance Monitoring 7. Lateral Thinking of Applicability along multiple domains Data : 1. Contextual Understanding - ETL / Data Manipulation / Visualization 2. IOT / Cloud / Big Data Know How 3. Model Management & Production Perspective for Predictive / NLP & Cognitive Sciences 4. Tool applicability & Evaluation to Delivery Education Qualification: 1. Masters in Statistics / Applied Mathematics / Economics / Econometrics & allied areas 2. M. Sc. Applied Statistics - Actuarials/ MSc from IITs 3. Relevant Certifications- SAS/Course Era (Good to have) Work Experience: 1. 2-5 years of pure data science experience 2. Hard Core Data Science Programming & Delivery using at least 3 languages 3. SAS / R/ Python / Open CV / Google TF e'

In [15]:
url='https://www.naukri.com/job-listings-data-scientist-data-analyst-business-analyst-inflexion-analytix-private-limited-mumbai-hyderabad-secunderabad-pune-gurgaon-gurugram-chennai-bangalore-bengaluru-0-to-3-years-100521000368?src=jobsearchDesk&sid=16231347341025209&xp=6&px=1'
driver.get(url)
jd = driver.find_element_by_xpath("//div[@class='dang-inner-html']").text
jd

"Job Role : Data Scientist/Data Analyst /Business Analyst\n\nLocation : Chennai/Bangalore/Hyderabad/Pune/Mumbai/Delhi\n\nGreetings from CAIA - Center for Artificial Intelligence & Advanced Analytics\n43% of companies experienced a high deficit of skilled resources with Advanced Analytical skills and AI implementing capabilities in year 2020. CAIA gives you a great opportunity to enter the world of future technologies and Innovations- Data Science, Analytics, AI, Data Visualization and Cloud Computing.\n\nWhile 2020 was a year like no other, we are living in an interesting times where data is reshaping the world, and businesses are rapidly adopting technology to gain an edge over others. Hence, there's a substantial increase in demand for technology professionals who can implement systems in data science, machine learning and AI in Tier 1 and Tier 2 organization's working closely with us.\n\nTo help you build a sustainable career we would like you to utilize data, software and Analytical approaches in Data Science and AI to up skill and get recruited into an organization appreciating your skilling journey.\nApplications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to make a career in Artificial Intelligence and Advanced Analytics and Data Science.\nIf you wish to make a shift in your career or undergo a career transition, upskilling is essential since it allows you to learn more about the domain and acquire the required skills.\n\nCall to schedule interview Monday -Saturday from 10:00 am to 7Pm\n\nAlexandria A - +91 76958 88879\nManigandan -+91 93444 57360\n\nEmail :\n\nalexandriaa@centerforaia.com\nmanigandan@centerforaia.com\n\nWhat is needed from you?\n\nFreshers who wish to start their career in Analytics and AI and professionals who wish to\nupskill or change their domain to analytics and emerging technologies are free to apply.\nAn Educational background in any one of the following- BE/B.Tech, ME/M Tech, MSc, BSc/MSc Math's and Statistics, B Com, BCA, BSc CS, BSC IT, MSC IT, MCA\nSkills relating to Mathematics/Statistics.\nNatural passion towards numbers, business, coding, Analytics and Artificial Intelligence, Machine Learning, visualization\nGood verbal and written communication skills\nAbility to understand domains in businesses across various sectors\n\n\nSelection procedure includes\n\nAptitude Test & Communication Exam - Online / Offline\nSQL/Python test - Online / Offline\n\nCandidates who clears the above will have one-one discussion with our Career Guidance Manager for further evaluation and processing of your Resume.\n\n\nAll the Shortlisted candidates will be eligible to continue the corporate training with CAIA\nWhat you can expect from us?\n\nYou will get trained on the following modules for a period of 12-14 weeks:\n\nSQL & PLSQL\nData Wrangling using Python\nData Visualization Using Power-BI\nStatistics for Machine Learning\nArtificial Intelligence, Data Interpretation\nSupervised & Unsupervised Learning,\nNLP & Deep Learning\nCloud Data Lake\nBusiness intelligence & Data Visualization\nSimulation Projects\nExpected Outcome?\n\nAt the end of the Training you are expected to be well versed with the following:\n\nAnalysis of large and complex data sets from multiple sources\nDevelopment and evaluation of data analytics models, algorithms and solutions\nUnderstanding/implementation of ML algorithms, performance tuning and reporting\nImplementation of algorithms to mine targeted data and the ability to convert data in to a business story\nTranslation of business requirements into technical requirements; Data extraction, preparation and transformation\nIdentification, development and implementation of statistical techniques and algorithms that address business challenges and adds value to the organization\nRequirement Analysis and communication of findings in the form of a meaningful story with the stakeholders\nFinding analytical solutions to abstract business issues.\nApply objective analysis of facts before coming to a conclusion\n\nAbout CAIA - Inflexion Analytix Private Limited\n\nCenter for Artificial Intelligence and Advanced Analytics (Center for AIA) is the brainchild of experienced and visionary alumni of IIT Madras and Bombay.\nDigital leaders - 5F World and Systech Solutions have joined hands to create a venture for architecting the future of society, workforce, governments and businesses. 5F World specializes in designing solutions around digital platforms and Systech Solutions has an expertise in architecting Artificial Intelligence and Advance Analytics solutions for Fortune 500 companies.\nOur Website : http://www.centerforaia.com/\n\nhttps://inflexion-analytix-private-limited.business.site/?m=true\n\nCenter for Artificial Intelligence & Advanced Analytics (CAIA) focuses on the following:\n\n1. Global Research on emerging trends, technologies and applications in AI and Advanced Analytics\n2. Advanced Training programs for readying the future ready workforce\n3. Solutions to herald the futuristic lifestyle and workspaces in the field of AI and Data Science."

In [16]:
url='https://www.naukri.com/job-listings-data-analytics-data-scientist-intern-work-from-home-talkvalley-llc-kolkata-bangalore-bengaluru-delhi-ncr-0-to-5-years-050621000128?src=jobsearchDesk&sid=16231347341025209&xp=7&px=1'
driver.get(url)
jd = driver.find_element_by_xpath("//div[@class='dang-inner-html']").text
jd

'We are a group of tenured professors from Tier-1 business schools in US universities. We teach machine learning and deep learning to master and PhD students. For our efforts with MentorStudents.org, we are looking to hire a team of interns who are interested in learning data science and analyze data under our supervision.\n\nHours commitment: at least 42.5 hrs/week\n\nDuration of the internship: 3 months\n\nRequired skills: Communication skills, Python, and OOP\n\nPerks (besides getting paid): Learn from professors who teach machine learning in the US\n+ internship completion certificate\n+ endorsement of your candidacy to US companies for a remote job via our placement business unit\n+ networking (check out https://MentorStudents.org)\n\nNext step / TEST for Selection:\nThis test will help you present your resume better and improve your employability. Hence, it is in your interest to work on this test. Create a tutorial in Google doc on how to create a timeline in Tableau Public. Use events from your resume as events for the timeline. You are encouraged to look at https://public.tableau.com/en-us/gallery for inspiration. Send your Google doc link at jobs [at] mentorstudents [dot] org. Make sure to make the link publicly accessible so that our team can evaluate your work.'

In [17]:
url='https://www.naukri.com/job-listings-sales-analytics-data-scientist-statestreet-global-advisor-pvt-ltd-bangalore-bengaluru-2-to-6-years-040621500512?src=jobsearchDesk&sid=16231347341025209&xp=8&px=1'
driver.get(url)
jd = driver.find_element_by_xpath("//div[@class='dang-inner-html']").text
jd

'Role Description\nThe role of the Data Scientist will be to work with Sales and Marketing teams to analyze and interpret complex data sets. We will drive impactful and creative data driven solutions. We will tackle complex problems through employing statistical analytical models, to enable productivity, profitability, and growth.\nResponsibilities\nCollaborate with team members to find opportunities for growth and value across the business.\nDesign and build modern machine learning and statistical methods or finding structure in disparate data sets.\nCraft predictive capabilities to increase and optimize campaigns, revenue, and other business outcomes.\nPerform exploratory and targeted data analyses through the systematic application of statistics and mathematics.\nIdentify data needs, drive methods and standards for data prep, data quality and governance.\nEffectively communicate technical analyses and results to non-technical partners through a variety of mediums, including Tableau dashboards, reports, and presentations.\nUse predictive modeling to increase and optimize customer experiences, pipeline conversions, campaign targeting and other business outcomes.\nCoordinate with different functional teams to implement models and monitor outcomes.\nDevelop processes and tools to monitor and analyze model performance and data accuracy .\nCoach and mentor aspiring data scientists across the organization.\nAbility to dream big, create, and have fun doing it.\nQualifications\nMasters degree in a quantitative discipline (Mathematics, Statistics, Computer Science, Economics, Finance, Financial Engineering) with 2-6 years of experience in an applied data science role.\nDemonstrable analytical skills with an emphasis on statistical modeling, decision science, and predictive analytics\nProgramming experience with implementation of statistical techniques in Matlab/R/Python/SAS or other languages\nKnowledge of a variety of machine learning techniques (clustering, decision tree learning, artificial neural networks, etc.) and their real-world advantages/drawbacks.\nMust have strong experience using a variety of data mining/data analysis methods using a variety of data tools, building and implementing models using/creating algorithms.\nMust have a proven ability to drive business results with their data-based insights.\nShould be comfortable working with a wide range of stakeholders and functional teams.\nThe right candidate will have a passion for discovering solutions hidden in large data sets and working with stakeholders to improve business outcomes.\nWorking knowledge of data visualization tools such as Tableau, Power BI, D3, to deliver output to the broader business community to improve decision-making and productivity\nAbility to take ownership and initiative, to negotiate, influence and build consensus and successfully navigate within a data driven environment of a leading global financial institution\nPrevious experience in Financial Services is desirable, but not necessary\nPersuasive and articulate in presenting complex ideas, simply'

In [18]:
url='https://www.naukri.com/job-listings-lead-data-scientist-profitwheel-data-technologies-private-limited-hyderabad-secunderabad-bangalore-bengaluru-mumbai-all-areas-2-to-4-years-240521006055?src=jobsearchDesk&sid=16231347341025209&xp=9&px=1'
driver.get(url)
jd = driver.find_element_by_xpath("//div[@class='dang-inner-html']").text
jd

'ROLE & RESPONSIBILITIES\n\nA sole contributor in his/her capacity, would be responsible for the following job roles:\n\nFormulates and leads guided, multifaceted analytic studies against large volumes of data.\nInterprets and analyzes data using exploratory mathematic and statistical techniques based on the scientific method.\nImplement new statistical or other mathematical methodologies as needed for specific models or analysis\nOptimize joint development efforts through appropriate database use and project design\nCoordinates research and analytic activities utilizing various data points (unstructured and structured) and employ programming to clean, massage, and organize the data.\nExperiments against data points, provide information based on experiment results and provide previously undiscovered solutions to command data challenges.\nLeads all data experiments tasked to the Data Science Team.\nCoordinates with Data Engineers to build data environments providing data identified by Data Analysts, Data Integrators, Knowledge Managers, and Intel Analysts.\nDevelops methodology and processes for prioritization and scheduling of projects.\nAnalyzes problems and determines root causes.\nDefines company data assets (data models), spark, sparkSQL, and hiveSQL jobs to populate data models.\nWorks closely with all business units and engineering teams to develop strategy for long term data platform architecture.\n\nDesired Candidate Profile\n\nSkills\n\nImplement new statistical or other mathematical methodologies as needed for specific models or analysis\nOptimize joint development efforts through appropriate database use and project design\nExcellent understanding of machine learning techniques and algorithms, such AS K-nn, naive bayes, SVM, decision forests, etc.\nExperience with common data science toolkits, such as R, Weka, NUMPY, MATLAB, etc excellence in at least one of these is highly desirable\nGreat COMMUNICATION SKILLS\nExperience with data visualisation tools, such as d3.JS, GGPLOT, ETC.\nProficiency in using query languages such as SQL, HIVE, PIG\nExperience with NoSQL databases, such as MONGODB, Cassandra, HBASE\n\n\nQualification Criteria\nBSc-IT, BE Graduate/MSC-IT/MCA/BCA/MCM\nWell-versed in software engineering principles, frameworks and technologies\nStrong oral and written communication skills\nStrong visual and logical reasoning and ability to work on complex projects\nVersatility, flexibility and willingness to work with changing priorities\n\nMust have Skills\n3 Years of experience with Data Science as a profession\n2 years of experience in Data Analytics and building inhouse tools for Data Storage / Analysis / ETL / ALGORITHM Matching / Statistical Modelling\nShould have at least 2 years of experience working with Python/ PERL/ C++/ Machine Language.\nShould have experience on working on AdTech/Mar-tech solutions\nShould have at least 2 years of experience with SQL, Reporting Systems, Analytics Engine\nMust have worked with R Studio\n\nPreferred Skills\nGood knowledge of Core PYTHON\nKnowledge and experience with Go Lang is an added advantage\nKnowledge and experience of HTML5, CCS and Javascript\nKnowledge of JAVA and Docker will be an added advantage.\n\n\nPerks and Benefits\n\nSalary no bar for the right candidate\nGreat culture to work with\nInteraction with Industry Leaders as Stakeholders\nPilot Team benefits - Long term fitment for the right personnel'

In [19]:
FILE_PATH_FOLDER = r"C:\Users\sumit\Dt\chromedriver.exe"
search_query = 'https://www.naukri.com/data-scientist-jobs?cityTypeGid=9508&ctcFilter=3to6'
driver = webdriver.Chrome(executable_path= r"C:\Users\sumit\Dt\chromedriver.exe")

In [20]:
driver.get(search_query)

In [21]:
#“Data Scientist” Job position in “Delhi/NCR” location salary = “3-6” lakhs
df2=pd.DataFrame(columns=['job-title', 'job-location', 'company_name', 'experience_required','url'] )#Creating empty data frame

#Getting the required data
for lst in tqdm(driver.find_elements_by_css_selector(".jobTuple.bgWhite.br4.mb-8")):  
    
    try:
        jt=lst.find_element_by_css_selector("a.title.fw500.ellipsis").text
    except:
        jt ="Nan"
    try:
        jl=lst.find_element_by_css_selector(".fleft.grey-text.br2.placeHolderLi.location").text
    except:
        jl="NaN"
    try:
        cn=lst.find_element_by_css_selector("a.subTitle.ellipsis.fleft").text
    except:
        cn="Nan"
    try:
        er=lst.find_element_by_css_selector(".fleft.grey-text.br2.placeHolderLi.experience").text
    except:
        er="NaN"
    try:
        url=lst.find_element_by_tag_name('a').get_attribute("href")
    except:
        url='NaN'

#Putting those data into dataframe
    df2.loc[len(df2)]=[jt,jl,cn,er,url]

100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 15.33it/s]

In [22]:
df2

  job-title job-location company_name experience_required  url
0       Nan          NaN          Nan                 NaN  NaN
1       Nan          NaN          Nan                 NaN  NaN
2       Nan          NaN          Nan                 NaN  NaN

In [23]:
FILE_PATH_FOLDER = r"C:\Users\sumit\Dt\chromedriver.exe"
search_query = 'https://www.flipkart.com/search?q=sunglasses&sid=26x&as=on&as-show=on&otracker=AS_QueryStore_OrganicAutoSuggest_1_10_na_na_na&otracker1=AS_QueryStore_OrganicAutoSuggest_1_10_na_na_na&as-pos=1&as-type=RECENT&suggestionId=sunglasses%7CSunglasses&requestId=df4b403a-eb1f-4ff8-8a60-5c58b4d0dd40&as-searchtext=sunglasses'
driver = webdriver.Chrome(executable_path= r"C:\Users\sumit\Dt\chromedriver.exe")

In [24]:
driver.get(search_query)

In [30]:
driver.find_element_by_xpath('//input[@class"_3704LK"]').send_keys('Sunglasses')
driver.find_element_by_xpath('//input[@class"L0Z3Pu"]').click()
time.sleep(5)

urls=[]
for i in driver.find_elements_by_xpath("//a[@class='_1LKT03']"):
    urls.append(i.get_attribute('href'))
    
Brand=[]
Product_description=[]
Price=[]
Discount=[]

for j in urls[0:3]:
    driver.get(j)
    for i in driver.find_elements_by_xpath("//div[@class='_2WkVRV']"): 
        Brand.append(i.text.replace('\n',''))
Brand

for j in urls[0:3]:
    driver.get(j)
    for i in driver.find_elements_by_xpath("//div[@class='IRpwTa']"):
        Product_description.append(i.text.replace('\n',''))
Product_description

for j in urls[0:3]:
    driver.get(j)
    for i in driver.find_elements_by_xpath("//div[@class='_30jeq3']"):
        Price.append(i.text.replace('\n',''))
Price

for j in urls[0:3]:
    driver.get(j)
    try:
    for i in driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']"):
        Discount.append(i.text.replace('\n',''))
    except:
        Discount.append("NA")
Discount        

fs=pd.DataFrame({})
fs['Brand']=Brand[:100]
fs['Product_description']=Product_description[:100]
fs['Price']=Price[:100]
fs['Discount']=Discount[:100]

IndentationError: expected an indented block (<ipython-input-30-a48ef2c022ba>, line 35)

In [ ]:
driver.find_element_by_xpath('//input[@class"_3704LK"]').send_keys('Sunglasses')
driver.find_element_by_xpath('//input[@class"L0Z3Pu"]').click()
time.sleep(5)

urls=[]
for i in driver.find_elements_by_xpath("//a[@class='_1LKT03']"):
    urls.append(i.get_attribute('href'))
    
phn_rating=[]
Review_summary=[]
Full_review=[]

for j in urls[0:3]:
    driver.get(j)
    for i in driver.find_elements_by_xpath("//div[@class='_2WkVRV']"): 
        Brand.append(i.text.replace('\n',''))
Brand

for j in urls[0:3]:
    driver.get(j)
    for i in driver.find_elements_by_xpath("//div[@class='IRpwTa']"):
        Product_description.append(i.text.replace('\n',''))
Product_description

for j in urls[0:3]:
    driver.get(j)
    for i in driver.find_elements_by_xpath("//div[@class='_30jeq3']"):
        Price.append(i.text.replace('\n',''))
Price

for j in urls[0:3]:
    driver.get(j)
    try:
    for i in driver.find_elements_by_xpath("//div[@class='_3Ay6Sb']"):
        Discount.append(i.text.replace('\n',''))
    except:
        Discount.append("NA")
Discount        

fs=pd.DataFrame({})
fs['Brand']=Brand[:100]
fs['Product_description']=Product_description[:100]
fs['Price']=Price[:100]
fs['Discount']=Discount[:100]